      INTEGER PLA_OBJTYPE_OFFSET 
      PARAMETER ( PLA_OBJTYPE_OFFSET = 10 )

      INTEGER PLA_VECTOR
      PARAMETER ( PLA_VECTOR = PLA_OBJTYPE_OFFSET + 1 )
      INTEGER PLA_MVECTOR                
      PARAMETER ( PLA_MVECTOR = PLA_OBJTYPE_OFFSET + 2 ) 
      INTEGER PLA_MATRIX                 
      PARAMETER ( PLA_MATRIX = PLA_OBJTYPE_OFFSET + 3 ) 
      INTEGER PLA_MSCALAR                
      PARAMETER ( PLA_MSCALAR = PLA_OBJTYPE_OFFSET + 4 ) 
      INTEGER PLA_PVECTOR                
      PARAMETER ( PLA_PVECTOR = PLA_OBJTYPE_OFFSET + 5 ) 
      INTEGER PLA_PMVECTOR               
      PARAMETER ( PLA_PMVECTOR = PLA_OBJTYPE_OFFSET + 6 ) 

      INTEGER PLA_TRANSPOSE_OFFSET
      PARAMETER ( PLA_TRANSPOSE_OFFSET = 20 )

      INTEGER PLA_NO_TRANSPOSE           
      PARAMETER ( PLA_NO_TRANSPOSE = PLA_TRANSPOSE_OFFSET + 1 )
      INTEGER PLA_NO_TRANS               
      PARAMETER ( PLA_NO_TRANS = PLA_TRANSPOSE_OFFSET + 1 )
      INTEGER PLA_TRANSPOSE              
      PARAMETER ( PLA_TRANSPOSE = PLA_TRANSPOSE_OFFSET + 2 )
      INTEGER PLA_TRANS                  
      PARAMETER ( PLA_TRANS = PLA_TRANSPOSE_OFFSET + 2 )
      INTEGER PLA_CONJUGATE_TRANSPOSE    
      PARAMETER ( PLA_CONJUGATE_TRANSPOSE = PLA_TRANSPOSE_OFFSET + 3 )
      INTEGER PLA_CONJ_TRANS             
      PARAMETER ( PLA_CONJ_TRANS = PLA_TRANSPOSE_OFFSET + 3 )
      INTEGER PLA_CONJUGATE              
      PARAMETER ( PLA_CONJUGATE = PLA_TRANSPOSE_OFFSET + 4 ) 
      INTEGER PLA_CONJ                   
      PARAMETER ( PLA_CONJ = PLA_TRANSPOSE_OFFSET + 4 )

      INTEGER PLA_OWNER_OFFSET
      PARAMETER ( PLA_OWNER_OFFSET = -30 )

      INTEGER PLA_ALL_ROWS               
      PARAMETER ( PLA_ALL_ROWS = PLA_OWNER_OFFSET - 1 )
      INTEGER PLA_ALL_COLS               
      PARAMETER ( PLA_ALL_COLS = PLA_OWNER_OFFSET - 2 )

      INTEGER PLA_SIDE_OFFSET
      PARAMETER ( PLA_SIDE_OFFSET = 40 )

      INTEGER PLA_SIDE_TOP               
      PARAMETER ( PLA_SIDE_TOP = PLA_SIDE_OFFSET  + 1 )
      INTEGER PLA_SIDE_BOTTOM            
      PARAMETER ( PLA_SIDE_BOTTOM = PLA_SIDE_OFFSET  + 2 )
      INTEGER PLA_SIDE_LEFT              
      PARAMETER ( PLA_SIDE_LEFT = PLA_SIDE_OFFSET  + 3 )
      INTEGER PLA_SIDE_RIGHT             
      PARAMETER ( PLA_SIDE_RIGHT = PLA_SIDE_OFFSET  + 4 )

      INTEGER PLA_SHAPE_OFFSET   
      PARAMETER ( PLA_SHAPE_OFFSET = 50 )

      INTEGER PLA_UPPER_TRIANGULAR       
      PARAMETER ( PLA_UPPER_TRIANGULAR = PLA_SHAPE_OFFSET + 1 )
      INTEGER PLA_UP_TRIAN               
      PARAMETER ( PLA_UP_TRIAN = PLA_SHAPE_OFFSET + 1 )
      INTEGER PLA_LOWER_TRIANGULAR       
      PARAMETER ( PLA_LOWER_TRIANGULAR = PLA_SHAPE_OFFSET + 2 )
      INTEGER PLA_LOWER_TRIAN            
      PARAMETER ( PLA_LOWER_TRIAN = PLA_SHAPE_OFFSET + 2 )
      INTEGER PLA_SHAPE_GENERAL          
      PARAMETER ( PLA_SHAPE_GENERAL = PLA_SHAPE_OFFSET + 3 )
      INTEGER PLA_SHAPE_LOWER_TRAPEZOIDAL  
      PARAMETER ( PLA_SHAPE_LOWER_TRAPEZOIDAL = PLA_SHAPE_OFFSET + 4 )
      INTEGER PLA_SHAPE_LOW_TRAP         
      PARAMETER ( PLA_SHAPE_LOW_TRAP = PLA_SHAPE_OFFSET + 4 )
      INTEGER PLA_SHAPE_UPPER_TRAPEZOIDAL  
      PARAMETER ( PLA_SHAPE_UPPER_TRAPEZOIDAL = PLA_SHAPE_OFFSET + 5 )
      INTEGER PLA_SHAPE_UP_TRAP          
      PARAMETER ( PLA_SHAPE_UP_TRAP = PLA_SHAPE_OFFSET + 5 )

      INTEGER PLA_FLOW_OFFSET  
      PARAMETER ( PLA_FLOW_OFFSET = 60 )

      INTEGER PLA_DIR_NOFLOW             
      PARAMETER ( PLA_DIR_NOFLOW = PLA_FLOW_OFFSET + 1 )
      INTEGER PLA_DIR_UP                 
      PARAMETER ( PLA_DIR_UP = PLA_FLOW_OFFSET + 2 )
      INTEGER PLA_DIR_DOWN               
      PARAMETER ( PLA_DIR_DOWN = PLA_FLOW_OFFSET + 3 )
      INTEGER PLA_DIR_LEFT               
      PARAMETER ( PLA_DIR_LEFT = PLA_FLOW_OFFSET + 4 )
      INTEGER PLA_DIR_RIGHT              
      PARAMETER ( PLA_DIR_RIGHT = PLA_FLOW_OFFSET + 5 )
      INTEGER PLA_TEMP_COL               
      PARAMETER ( PLA_TEMP_COL = PLA_FLOW_OFFSET + 6 )
      INTEGER PLA_TEMP_ROW               
      PARAMETER ( PLA_TEMP_ROW = PLA_FLOW_OFFSET + 7 )

      INTEGER PLA_API_OFFSET  
      PARAMETER ( PLA_API_OFFSET = 70 )
 
      INTEGER PLA_MODE_CLOSED            
      PARAMETER ( PLA_MODE_CLOSED = PLA_API_OFFSET + 1 )
      INTEGER PLA_MODE_OPEN              
      PARAMETER ( PLA_MODE_OPEN = PLA_API_OFFSET + 2 )
      INTEGER PLA_STATE_API_ACTIVE       
      PARAMETER ( PLA_STATE_API_ACTIVE = PLA_API_OFFSET + 3 )
      INTEGER PLA_STATE_NORMAL           
      PARAMETER ( PLA_STATE_NORMAL = PLA_API_OFFSET + 4 )

      INTEGER PLA_OP_OFFSET  
      PARAMETER ( PLA_OP_OFFSET = 80 )

      INTEGER PLA_OP_MAT_PAN             
      PARAMETER ( PLA_OP_MAT_PAN = PLA_OP_OFFSET + 1 )
      INTEGER PLA_OP_PAN_MAT             
      PARAMETER ( PLA_OP_PAN_MAT = PLA_OP_OFFSET + 2 )
      INTEGER PLA_OP_PAN_PAN             
      PARAMETER ( PLA_OP_PAN_PAN = PLA_OP_OFFSET + 3 )
      INTEGER PLA_OP_PAN_TRIAN_MAT       
      PARAMETER ( PLA_OP_PAN_TRIAN_MAT = PLA_OP_OFFSET + 4 )
      INTEGER PLA_OP_SYM_PAN_PAN         
      PARAMETER ( PLA_OP_SYM_PAN_PAN = PLA_OP_OFFSET + 5 )
      INTEGER PLA_OP_TRIAN_MAT_PAN       
      PARAMETER ( PLA_OP_TRIAN_MAT_PAN = PLA_OP_OFFSET + 6 )
      INTEGER PLA_OP_ALL_ALG             
      PARAMETER ( PLA_OP_ALL_ALG = PLA_OP_OFFSET + 7 )

      INTEGER PLA_PROJ_OFFSET  
      PARAMETER ( PLA_PROJ_OFFSET = 90 )

      INTEGER PLA_PROJ_ONTO_COL          
      PARAMETER ( PLA_PROJ_ONTO_COL = PLA_PROJ_OFFSET + 1 )
      INTEGER PLA_PROJ_ONTO_ROW          
      PARAMETER ( PLA_PROJ_ONTO_ROW = PLA_PROJ_OFFSET + 2 )

      INTEGER PLA_DIAG_OFFSET  
      PARAMETER ( PLA_DIAG_OFFSET = 100 )

      INTEGER PLA_UNIT_DIAG              
      PARAMETER ( PLA_UNIT_DIAG = PLA_DIAG_OFFSET + 1 )
      INTEGER PLA_NONUNIT_DIAG           
      PARAMETER ( PLA_NONUNIT_DIAG = PLA_DIAG_OFFSET + 2 )
      INTEGER PLA_ZERO_DIAG              
      PARAMETER ( PLA_ZERO_DIAG = PLA_DIAG_OFFSET + 3 )

      INTEGER PLA_DUMMY         
      PARAMETER ( PLA_DUMMY = 0 )
      INTEGER PLA_SUCCESS       
      PARAMETER ( PLA_SUCCESS = 0 )
      INTEGER PLA_ALIGN_FIRST  
      PARAMETER ( PLA_ALIGN_FIRST = -200 )
      INTEGER PLA_DIM_ALL      
      PARAMETER ( PLA_DIM_ALL = -201 )
      INTEGER PLA_INHERIT      
      PARAMETER ( PLA_INHERIT = -202 )
      INTEGER PLA_UNDEFINED    
      PARAMETER ( PLA_UNDEFINED = -203 )



